image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: Script

install:
  - java -jar ./artifacts/app-card-delivery.jar &
  - chmod +x gradlew


build_script:
  - Dselenide.headless=true
 - ./gradlew test --info
